apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: allureopts.allure-docker-service.group
spec:
  group: allure-docker-service.group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                expose_type:
                  type: string
                  enum: 
                    - ingress
                    - nodeport
                nodeport_api_port:
                  type: integer
                nodeport_ui_port:
                  type: integer
                nodeport_ext_ip:
                  type: string
                ingress_fqdn:
                  type: string
              required:
                - expose_type
      additionalPrinterColumns:
        - name: TYPE
          type: string
          priority: 0
          jsonPath: .spec.expose_type
          description: expose_type.
        - name: DEPLOYMENT
          type: string
          priority: 0
          jsonPath: .status.create_allure.DEPLOYMENT
          description: The deployment created(from fn create_allure).
        - name: UI
          type: string
          priority: 0
          jsonPath: .status.create_allure.UI
          description: The ui url(from fn create_allure).
  scope: Namespaced
  names:
    plural: allureopts
    singular: allureopt
    kind: AllureOpt
    shortNames:
    - allure
---
#
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: test-opt
#  namespace: test
#---
#
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: test-opt
#  namespace: test
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: cluster-admin
#subjects:
#  - kind: ServiceAccount
#    name: test-opt
#    namespace: test
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: test-opt
#  namespace: test
#spec:
#  selector:
#    matchLabels:
#      app: test-opt
#  template:
#    metadata:
#      labels:
#        app: test-opt
#    spec:
#      serviceAccountName: test-opt
#      containers:
#      - image: mting/testopt
#        name: test-opt