apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: allureopts.allure-docker-service.group
spec:
  group: allure-docker-service.group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                expose_type:
                  type: string
                  enum: 
                    - ingress
                    - nodeport
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                nodeport_api_port:
                  type: integer
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                nodeport_ui_port:
                  type: integer
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                nodeport_ext_ip:
                  type: string
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                ingress_fqdn:
                  type: string
                  x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                storage_class:
                  type: string
                loop_timer:
                  type: integer
                loop_pytest_ver:
                  type: string
              required:
                - expose_type
                - storage_class
      additionalPrinterColumns:
        - name: TYPE
          type: string
          priority: 0
          jsonPath: .spec.expose_type
          description: expose_type.
        - name: ALLURE_DEPLOYMENT
          type: string
          priority: 0
          jsonPath: .status.create_allure.ALLURE_DEPLOYMENT
          description: The deployment created(from fn create_allure).
        - name: UI
          type: string
          priority: 0
          jsonPath: .status.create_allure.UI
          description: The ui url(from fn create_allure).
        - name: LOOP_PYTEST_DEPLOYMENT
          type: string
          priority: 0
          jsonPath: .status.create_allure.LOOP_PYTEST_DEPLOYMENT
        - name: LOOP_TIMER
          type: integer
          priority: 0
          jsonPath: .status.create_allure.LOOP_TIMER
        - name: LOOP_PYTEST_VER
          type: string
          priority: 0
          jsonPath: .status.create_allure.LOOP_PYTEST_VER
  scope: Namespaced
  names:
    plural: allureopts
    singular: allureopt
    kind: AllureOpt
    shortNames:
    - allure
