apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: allureopts.allure-docker-service.group
spec:
  group: allure-docker-service.group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              x-kubernetes-validations:
                - message: expose_type ingress must has ingress_fqdn, expose_type nodeport must has nodeport_api_port, nodeport_ui_port and nodeport_ext_ip
                  rule: "self.expose_type=='ingress' && has(self.ingress_fqdn) || self.expose_type=='nodeport' && has(self.nodeport_api_port) && has(self.nodeport_ui_port) && has(self.nodeport_ext_ip)"
                - message: Value is immutable
                  rule: self.expose_type == oldSelf.expose_type
                - message: Value is immutable
                  rule: self.nodeport_api_port == oldSelf.nodeport_api_port
                - message: Value is immutable
                  rule: self.nodeport_ui_port == oldSelf.nodeport_ui_port
                - message: Value is immutable
                  rule: self.nodeport_ext_ip == oldSelf.nodeport_ext_ip
                - message: Value is immutable
                  rule: self.ingress_fqdn == oldSelf.ingress_fqdn
                - message: Value is immutable
                  rule: self.storage_class == oldSelf.storage_class
                - message: Value is immutable
                  rule: self.loop_timer == oldSelf.loop_timer
                - message: Value is immutable
                  rule: self.pvc_size == oldSelf.pvc_size
                - message: Value is immutable
                  rule: self.keep_history_num == oldSelf.keep_history_num
              properties:
                expose_type:
                  type: string
                  enum: 
                    - ingress
                    - nodeport
                nodeport_api_port:
                  type: integer 
                nodeport_ui_port:
                  type: integer
                nodeport_ext_ip:
                  type: string
                ingress_fqdn:
                  type: string
                storage_class:
                  type: string
                pvc_size:
                  type: string
                loop_timer:
                  type: integer
                loop_pytest:
                  type: boolean
                  enum: 
                    - yes
                    - no
                loop_pytest_image:
                  type: string
                keep_history_num:
                  type: integer
                pytest_cmd:
                  type: string
              required:
                - expose_type
                - storage_class
                - loop_pytest
                - loop_timer
                - loop_pytest_image
                - pvc_size
                - pytest_cmd
                - keep_history_num
      additionalPrinterColumns:
        - name: TYPE
          type: string
          priority: 0
          jsonPath: .spec.expose_type
        - name: PVC_SIZE
          type: string
          priority: 0 
          jsonPath: .spec.pvc_size
        - name: ALLURE_DEPLOYMENT
          type: string
          priority: 0
          jsonPath: .status.create_allure.ALLURE_DEPLOYMENT
        - name: UI
          type: string
          priority: 0
          jsonPath: .status.create_allure.UI
        - name: LOOP_PYTEST_DEPLOYMENT
          type: string
          priority: 0
          jsonPath: .status.create_allure.LOOP_PYTEST_DEPLOYMENT
        - name: LOOP_TIMER
          type: integer
          priority: 0
          jsonPath: .spec.loop_timer
        - name: LOOP_PYTEST
          type: boolean
          priority: 0
          jsonPath: .spec.loop_pytest
        - name: LOOP_PYTEST_IMAGE
          type: string
          priority: 0
          jsonPath: .spec.loop_pytest_image
        - name: PYTEST_CMD
          type: string
          priority: 0
          jsonPath: .spec.pytest_cmd
  scope: Namespaced
  names:
    plural: allureopts
    singular: allureopt
    kind: AllureOpt
    shortNames:
    - allure
---

apiVersion: v1
kind: Namespace
metadata:
  name: allure
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: allureopt
  namespace: allure
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allureopt
  namespace: allure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: allureopt
    namespace: allure
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: allureopt
  namespace: allure
spec:
  selector:
    matchLabels:
      app: allureopt
  template:
    metadata:
      labels:
        app: allureopt
    spec:
      serviceAccountName: allureopt
      containers:
      - image: mting/allureopt:0.4
        name: allureopt