apiVersion: allure-docker-service.group/v1
kind: AllureOpt
metadata:
  name: allure
spec:
#  expose_type: nodeport
  expose_type: ingress
  nodeport_api_port: 30008
  nodeport_ui_port: 30009
  nodeport_ext_ip: 192.168.88.70
  keep_history_num: 500
  ingress_fqdn: allure.test
  storage_class: nfs-client
  pvc_size: 5Gi
  loop_timer: 30
  loop_pytest: yes
  loop_pytest_image: "mting/loop_pytest:0.4" 
  pytest_cmd: "python -m pytest test.py -v -s"
