apiVersion: allure-docker-service.group/v1
kind: AllureOpt
metadata:
  name: allure
spec:
  expose_type: nodeport
  nodeport_api_port: 30008
  nodeport_ui_port: 30009
  nodeport_ext_ip: 192.168.88.70
  ingress_ui_fqdn:
  ingress_api_fqdn:


  